# Generated by Django 4.1.7 on 2023-04-11 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_expense_createdat_alter_expense_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='spotRate',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
