# Generated by Django 4.1.7 on 2023-04-11 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_expense_spotrate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
