# Generated by Django 4.1.7 on 2023-04-26 06:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_alter_expense_createdat_alter_expense_updatedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='subCategory',
            field=models.CharField(max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
