# Generated by Django 4.1.7 on 2023-04-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_expense_subcategory_alter_expense_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
