# Generated by Django 4.1.7 on 2023-04-27 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_expense_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
